site_name: "BrainSight"
site_url: http://127.0.0.1:8000/brainsight  # Set to empty string false if deploying to as files
site_description: "BrainSight"
site_author: "Machine Medicine Team"
copyright: "2024 MMT"
use_directory_urls: true  # Set to false if deploying to as files
repo_name: brainsight
repo_url: https://github.com/machinemedicine/brainsight
edit_uri: blob/master/docs/

theme:
  name: material
  locale: en
  logo: https://i.ibb.co/NmYzF03/MMT-Inverted.png
  favicon: https://i.ibb.co/NmYzF03/MMT-Inverted.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
  palette:
    scheme: mmt
extra_css:
  - stylesheets/extra.css

nav:
  - Home:
    - "Welcome": index.md
    - "Install": install.md
    - "Getting started": demo.md
  - API Reference: reference/

watch:
  - brainsight/

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_doc_stubs.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # https://mkdocstrings.github.io/python/usage/
            docstring_style: numpy
            show_signature_annotations: True
            show_source: False
            # show_if_no_docstring: True
            merge_init_into_class: True
            show_symbol_type_toc: True
            show_symbol_type_heading: True
        
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

markdown_extensions:
  - pymdownx.highlight
  - toc:
      permalink: "#"